apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-getter
spec:
  replicas: 1
  selector:
    matchLabels:
      application: wiki-getter
  template:
    metadata:
      labels:
        application: wiki-getter
    spec:
      containers:
      - name: server
        image: quay.io/ajssmith/wiki-getter
        imagePullPolicy: Always
        ports:
          - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-getter
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    application: wiki-getter
  type: LoadBalancer